# Generated by Django 3.1.4 on 2020-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='meta_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HQ', 'High Quality'), ('BQ', 'Best Quality'), ('MQ', 'Mid Quality')], max_length=2),
        ),
    ]
